name: foocuszone_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 # Added for state management
  shared_preferences: ^2.0.0 # Added for local storage
  flutter_local_notifications: ^17.0.0 # Added for local notifications
  audioplayers: ^6.0.0 # Added for sound effects
  intl: ^0.19.0 # Added for date/time formatting
  http: ^1.1.0 # Added for API requests
  flutter_dotenv: ^5.1.0 # Added for environment variables
  # uuid: ^4.4.0 # Eğer uuid kullanmak isterseniz bu satırı uncomment edin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/ # Make sure this line exists and you add sound files here
    - .env # Add the .env file to assets
    # Example:
    # - assets/sounds/default_alarm.mp3
    # - assets/sounds/calm_chime.mp3
    # - assets/sounds/short_break.mp3
